# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0003_auto_20170411_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
