# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chimp', '0004_auto_20170411_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_email', models.IntegerField(default=0)),
                ('remaining_email', models.IntegerField(default=0)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mailing_List',
            new_name='MailingList',
        ),
        migrations.RenameModel(
            old_name='Template_List',
            new_name='TemplateList',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
