# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0005_auto_20170411_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='package',
            field=models.CharField(choices=[('BASIC', 'basic'), ('STANDARD', 'standard'), ('ADVANCE', 'advance')], max_length=10, null=True),
        ),
    ]
