# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0006_userprofile_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='package',
            field=models.CharField(choices=[('BASIC', 'basic'), ('STANDARD', 'standard'), ('ADVANCE', 'advance')], default='BASIC', max_length=10, null=True),
        ),
    ]
