# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0007_auto_20170411_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mailing_list_path',
            field=models.FileField(upload_to='uploads/excels/'),
        ),
        migrations.AlterField(
            model_name='templatelist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chimp.Category'),
        ),
    ]
