# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0010_auto_20170418_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelist',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
