# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0013_mailinglist_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
