# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0015_auto_20170427_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatelist',
            old_name='file',
            new_name='path',
        ),
    ]
