# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:35
from __future__ import unicode_literals

import chimp.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0016_auto_20170428_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mailing_list_path',
            field=models.FileField(upload_to='uploads/excels/', validators=[chimp.validation.validate_file_extension]),
        ),
    ]
