# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0018_auto_20170428_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelist',
            name='file',
            field=models.FileField(upload_to='uploads/templates'),
        ),
        migrations.AlterField(
            model_name='templatelist',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
