# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0020_auto_20170501_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglist',
            old_name='mailing_list_path',
            new_name='file',
        ),
    ]
