# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0026_auto_20170503_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
