# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 14:59
from __future__ import unicode_literals

import chimp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0027_mailinglist_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mailing_list_path',
            field=models.FileField(upload_to=chimp.models.get_mailingfile_path),
        ),
        migrations.AlterField(
            model_name='templatelist',
            name='file',
            field=models.FileField(upload_to=chimp.models.get_templatesfile_path),
        ),
    ]
