# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimp', '0029_auto_20170504_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('PROMOTIONAL', 'promotional'), ('ADVERTISEMENT', 'advertisement'), ('SOCIAL', 'social'), ('OTHER', 'others')], max_length=30),
        ),
    ]
